nodejs/release-cloudflare-worker

- .github/workflows/format.yml
- .github/workflows/test.yml
see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.
> fix: ci checks out wrong code

- src/handlers/get.ts
- src/util.ts
- tests/e2e/directory.test.ts
- tests/e2e/test-data/expected-html/dist.html
Fixes: https://github.com/nodejs/release-cloudflare-worker/issues/25
> fix: redirect when missing trailing slash

- src/worker.ts
We weren't awaiting the handlers causing any errors that happen past a point to be caught by Workerd rather than our try/catch block in the entrypoint
> fix: await handlers so any errors are caught

- src/util.ts
- tests/unit/util.test.ts
Fixes: https://github.com/nodejs/release-cloudflare-worker/issues/50
> fix: add missing redirect handling

- package-lock.json
- package.json
- src/env.ts
- src/worker.ts
Note: need to add the dsn under the SENTRY_DSN secret.
Was going to use Sentry's official client `@sentry/node` , but I'm not sure if it's compatible with Workers. `toucan-js` is specifically meant as a Sentry client for Workers, and it's even being used in some of Cloudflare's own modules https://github.com/cloudflare/worker-sentry/blob/74ffc72bbd305fcbf832f873342967ae9de7088f/package.json#L17
> src: report errors to sentry

- src/util.ts
- tests/unit/util.test.ts
> fix: don't treat vX.X.X folders as files

- src/util.ts
- tests/unit/util.test.ts
> fix: don't treat file paths with 7z extension as directories

- src/util.ts
- tests/unit/util.test.ts
> fix: make `isExtensionless` check if the last `.` is before the last `/`

- src/handlers/get.ts
- src/handlers/post.ts
- src/handlers/strategies/cachePurge.ts
- src/handlers/strategies/directoryListing.ts
- src/handlers/strategies/serveFile.ts
- src/utils/cache.ts
- src/utils/object.ts
- src/utils/path.ts
- src/utils/request.ts
- tests/unit/index.test.ts
- tests/unit/utils/object.test.ts
- tests/unit/utils/path.test.ts
Separate utils into different files based off of what they're used for, cleaning up the logic in some of the utils (e.g. `mapBucketPathToUrlPath`) will be in a separate pr
> cleanup: separate utils into separate files

- package-lock.json
- package.json
Resolves warnings generated when running the tests. Required updating tsx to ^4.7.2
> tests: use `--import=tsx` for tests

- src/constants/limits.ts
- src/constants/r2Prefixes.ts
- src/handlers/get.ts
- src/providers/provider.ts
- src/providers/r2Provider.ts
- src/utils/path.ts
- src/utils/provider.ts
- tests/unit/utils/path.test.ts
Adds the Provider interface and most of the implementation of R2Provider as discussed in #111. Note that as of right now the provider isn't being used, this will happen in future prs.
> src: implement R2Provider

- .github/workflows/update-links.yml
From what I've gathered, the linker gets updated for each new LTS at the very least
> actions: auto update nodejs-latest-linker package

- src/routes/index.ts
Quick fix, responses from fetch() are immutable and so the cache middleware throws when adding headers. Will get a better fix soon^tm
> src: don't cache origin requests

- src/middleware/cacheMiddleware.ts
Investigating why staging always falls back to the origin for directory listings after #125, this will _hopefully_ fix things
Sentry ref: https://nodejs-org.sentry.io/issues/5799625624/
> src: don't add cache headers

- .github/workflows/promote.yml
- package.json
- scripts/constants.mjs
- scripts/promote-release.js
- scripts/promote-release.mjs
Re https://github.com/nodejs/build/issues/3838#issuecomment-2394864184
> actions: promote release action

- .github/workflows/update-links.yml
Ensure updated version of nodejs-latest-linker writes to package.json as well as package-lock.json, as in #150 only the lock was updated.
> actions: pass --save to nodejs-latest-linker update

- src/middleware/r2Middleware.ts
- src/providers/r2Provider.ts
Fixes #148
Re https://nodejs-org.sentry.io/issues/6028971646/?project=4506191181774848
> src: fix range errors

- src/middleware/methodNotAllowedMiddleware.ts
- src/routes/index.ts
- src/routes/router.ts
- tests/e2e/file.test.ts
Re the unhandled errors reported in Cloudflare dash
> src: send a 405 for anything other than GET or HEAD

- src/middleware/r2Middleware.ts
These appear to be from clients sending chunks of the directory listing html as the path in the url (e.g. `https://nodejs.org/dist/v21.2.0-aix-ppc64.tar.gz'%3Enode-v21.2.0-aix-ppc64.tar.gz%3C/a%3E%3C/` -> `https://nodejs.org/dist/v21.2.0-aix-ppc64.tar.gz'>node-v21.2.0-aix-ppc64.tar.gz</a></`)
Closes #165
> src: handle object name errors more gracefully

- COLLABORATOR_GUIDE.md
- package-lock.json
- package.json
Zod isn't being used anywhere in the worker
> npm: remove zod dependency

- src/constants/contentTypeOverrides.json
- src/providers/r2Provider.ts
nginx serves .tab files as `text/plain` but the worker serves them as `application/octet-stream` https://direct.nodejs.org/dist/index.tab
> fix: serve index.tab files as text files

- .github/workflows/deploy.yml
- .github/workflows/format.yml
- .github/workflows/test.yml
Adds a timeout in case jobs don't quit by themselves for whatever reason
Re https://github.com/nodejs/release-cloudflare-worker/actions/runs/12996566677/job/36245623529?pr=234 which was running for 3 hours
> actions: add timeout to jobs

- src/utils/request.ts
- tests/e2e/file.test.ts
- tests/unit/utils/request.test.ts
> fix: handle invalid dates properly

- .github/workflows/notify-on-force-push.yml
> actions: add notify-on-push action

- src/providers/r2Provider.ts
- tests/e2e/file.test.ts
Closes nodejs/build#4030
Misinterpretation of the docs, precondition failures due to `if-none-match` return a 412 for unsafe http methods (aka those that modify things on the sever-side). For safe methods (GET, HEAD), they return a 304.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match
> fix: don't return 412 for if-none-match failures

- scripts/build-r2-symlinks.mjs
- src/constants/fileSymlinks.json
- src/middleware/r2Middleware.ts
- src/routes/index.ts
Fixes nodejs/node#57485
Probably a nicer way to do this, but this works for now just to fix the issue
Note we still need nodejs/build#4044 for the worker to actually get the request
> fix: support `/node-config-schema.json`

- COLLABORATOR_GUIDE.md
- CONTRIBUTING.md
- GOVERNANCE.md
The major change here is removing the `What's the process for becoming a Collaborator?` section from `CONTRIBUTING.md` and replacing it with a link to nodejs.org's `GOVERNANCE.md`. This was done for two reasons:
1. It's out of sync with the requirements described in the website's governance doc
2. It makes sense to have a single source of truth for the requirements
This also fixes some grammatical errors and broken links.
> doc: update contributing & collaborator guide to point to website repo

- .github/workflows/update-links.yml
Should stop the workflow racing itself as seen in #439 + #440
> actions: restrict concurrency on update-links workflow

- .github/dependabot.yml
https://github.com/nodejs/web-team/issues/25
> ci: set 3-day cooldown for Dependabot updates

- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/deploy.yml
- .github/workflows/format.yml
- .github/workflows/test.yml
- .github/workflows/update-links.yml
Primarily, opening this to pin actions/setup-node to a specific hash, unsure why we were still using a loose major version tag.
But, also, this adds a bunch of missing version comments after hash-pinned actions (and does a tiny bit of nitpicky tidying up of step/job names).
> ci: pin actions/setup-node to hash + add missing version comments

- .github/workflows/codeql.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
- .github/workflows/update-links.yml
- package.json
- wrangler.jsonc
Fix deployment warnings, format yml files
> chore: fix deployment warnings

- .github/workflows/deploy.yml
- src/middleware/throwMiddleware.ts
- src/routes/index.ts
- src/routes/router.ts
- src/worker.ts
> actions: update deploy egress policy + refactor error-throwing route
